public class CallMD_MemberProviderTriggerHandler {

    public static void afterInsertBenefitProvider(List<Providers__c> lstProvider){
        
    
        for(Providers__c prov:lstProvider){
            
        }
        
    }
    
    public static void afterUpdateBenefitProvider(List<Providers__c> lstProvider){
        
         for(Providers__c prov:lstProvider){
            
        }
    }
    
}